"use client";
import {useState,useEffect,useCallback,useRef} from "react";
import {Plus,Flame,ArrowUpRight,Droplets,SlidersHorizontal,ChevronLeft,ChevronRight,Sun,Sunrise,Moon,Apple,Pencil,Trash2,Check,Target,RotateCcw,CloudCheck,LoaderCircle,CalendarDays,X,PawPrint,Leaf,Sparkles,Candy} from "lucide-react";
import {Progress} from "@/components/ui/progress";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogClose} from "@/components/ui/dialog";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from "@/components/ui/combobox";
import {Empty,EmptyDescription} from "@/components/ui/empty";
import {toast,Toaster} from "sonner";
import {NutritionPet} from "@/components/nutrition-pet";
import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
import {foodKinds,foodKindInfo,initialPet,pets,type FoodKind,type PetReaction,type PetSpecies} from "@/lib/pet";
import {meals,defaultGoals,foods,localDate,shiftDate,totalEntries,format,scale,type Entry,type Goals,type Journal,type Meal,type Nutrients} from "@/lib/nutrition";
const icons=[Sunrise,Sun,Moon,Apple];
const nutrients=[["calories","热量","kcal"],["protein","蛋白质","g"],["carbs","碳水化合物","g"],["fat","脂肪","g"]] as const;
const blank={name:"",grams:"100",calories:"",protein:"",carbs:"",fat:""};
async function api<T=unknown>(method:string,body?:unknown,date?:string):Promise<T>{const r=await fetch("/api/journal"+(date?"?date="+date:""),{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Object.assign(new Error((data as {error?:string}).error||"暂时无法连接，请稍后重试。"),{status:r.status});return data as T}
export default function Home(){
 const [date,setDate]=useState("");const [today,setToday]=useState("");const [data,setData]=useState<Journal>({entries:[],waterEntries:[],goals:defaultGoals,goalsSet:false});
 const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState("");const [needsLogin,setNeedsLogin]=useState(false);const [busy,setBusy]=useState(false);const busyRef=useRef(false);const requestId=useRef(0);
 const [foodKind,setFoodKind]=useState<FoodKind>("regular");const [petReaction,setPetReaction]=useState<PetReaction|null>(null);
 const [foodOpen,setFoodOpen]=useState(false);const [goalOpen,setGoalOpen]=useState(false);const [meal,setMeal]=useState<Meal>("早餐");const [tab,setTab]=useState("common");const [selected,setSelected]=useState<string|null>(null);const [grams,setGrams]=useState("100");const [custom,setCustom]=useState(blank);const [entryId,setEntryId]=useState("");const [editing,setEditing]=useState(false);const [goalDraft,setGoalDraft]=useState<Goals>(defaultGoals);const [formError,setFormError]=useState("");
 useEffect(()=>{const sync=()=>setToday(localDate());sync();setDate(localDate());const t=setInterval(sync,60000);return()=>clearInterval(t)},[]);
 const refresh=useCallback(async(d:string)=>{const id=++requestId.current;setLoading(true);setLoadError("");try{const next=await api<Journal>("GET",undefined,d);if(id===requestId.current){setData(next);setNeedsLogin(false)}}catch(e){if(id===requestId.current){setLoadError((e as Error).message);setNeedsLogin((e as {status?:number}).status===401)}}finally{if(id===requestId.current)setLoading(false)}},[]);
 useEffect(()=>{setPetReaction(null);if(date)void refresh(date)},[date,refresh]);
 const totals=totalEntries(data.entries);const g=data.goals;const water=data.waterEntries.reduce((a,e)=>a+e.amount,0);const progress=Math.round(totals.calories/g.calories*100);const ready=!!date&&!loading&&!loadError&&!busy;const selectedFood=foods.find(f=>f.name===selected);
 const species=data.petSpecies??"capybara";const companion=pets[species];
 const readable=date?new Date(date+"T12:00:00").toLocaleDateString("zh-CN",{month:"long",day:"numeric",weekday:"long"}):"今天";
 const startFood=(m:Meal)=>{setMeal(m);setFoodKind("regular");setTab("common");setSelected(null);setGrams("100");setCustom(blank);setEntryId(crypto.randomUUID());setEditing(false);setFormError("");setFoodOpen(true)};
 const startEdit=(e:Entry)=>{setMeal(e.meal);setFoodKind(e.foodKind??"regular");setTab("custom");setCustom({name:e.name,grams:String(e.grams),calories:String(e.calories),protein:String(e.protein),carbs:String(e.carbs),fat:String(e.fat)});setEntryId(e.id);setEditing(true);setFormError("");setFoodOpen(true)};
 const startGoals=()=>{setGoalDraft({...g});setFormError("");setGoalOpen(true)};
 async function mutate(method:string,body:unknown,onSuccess?:()=>void){if(busyRef.current)return;busyRef.current=true;setBusy(true);setFormError("");try{await api(method,body);onSuccess?.();await refresh(date);return true}catch(e){setFormError((e as Error).message);toast.error((e as Error).message);return false}finally{busyRef.current=false;setBusy(false)}}
 const switchPet=(next:PetSpecies)=>{if(next===species)return;void mutate("PUT",{kind:"pet",species:next},()=>{setPetReaction(null);toast.success(pets[next].name+"来陪你啦")})};
 const saveFood=async(e:React.FormEvent)=>{e.preventDefault();let payload:Omit<Entry,"id"|"date"|"meal">;if(tab==="common"){if(!selectedFood||!Number.isFinite(Number(grams))||Number(grams)<=0){setFormError("请选择食物并填写大于 0 的重量。");return}payload={name:selectedFood.name,grams:Number(grams),calories:scale(selectedFood.calories,Number(grams)),protein:scale(selectedFood.protein,Number(grams)),carbs:scale(selectedFood.carbs,Number(grams)),fat:scale(selectedFood.fat,Number(grams)),source:selectedFood.source}}else{payload={name:custom.name.trim(),grams:Number(custom.grams),calories:Number(custom.calories),protein:Number(custom.protein),carbs:Number(custom.carbs),fat:Number(custom.fat),source:""};if(!payload.name||Object.values(custom).some(v=>v.trim()==="")){setFormError("请填写食物名称、重量和完整营养数据。");return}}
 await mutate(editing?"PUT":"POST",{kind:"entry",id:entryId,date,meal,...payload,foodKind},()=>{setFoodOpen(false);if(editing)setPetReaction(null);toast.success(editing?"记录已更新":"已加入"+meal+" · "+companion.name+"收到啦");if(!editing){setPetReaction({id:crypto.randomUUID(),kind:foodKind});requestAnimationFrame(()=>document.getElementById("pet-home")?.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"instant":"smooth",block:"center"}))}})};
 const deleteEntry=async(e:Entry)=>{await mutate("DELETE",{kind:"entry",id:e.id},()=>{setPetReaction(null);toast("记录已删除",{action:{label:"撤销",onClick:()=>{void mutate("POST",{kind:"entry",...e})}}})})};
 const drink=()=>void mutate("POST",{kind:"water",id:crypto.randomUUID(),date,amount:250},()=>{toast.success("已记录 250 ml 饮水");setPetReaction({id:crypto.randomUUID(),kind:"water"})});
 const undoWater=()=>{const last=data.waterEntries.at(-1);if(last)void mutate("DELETE",{kind:"water",id:last.id},()=>{setPetReaction(null);toast.success("已撤销上一杯")})};
 const saveGoals=async(e:React.FormEvent)=>{e.preventDefault();await mutate("PUT",{kind:"goals",date,...goalDraft},()=>{setGoalOpen(false);toast.success("目标已保存，从所选日期起生效")})};
 const stateRef=useRef({date,data,ready,startFood});stateRef.current={date,data,ready,startFood};
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();for(const tool of [
 {name:"get_daily_nutrition",title:"查看当日营养记录",description:"读取当前选中日期的已保存饮食、饮水和营养目标。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("不接受额外参数");const s=stateRef.current;if(!s.ready)throw new Error("记录尚未准备好");return {date:s.date,...s.data,totals:totalEntries(s.data.entries)}}},
 {name:"start_food_entry",title:"开始记录饮食",description:"打开指定餐次的饮食录入表单，不会自动保存记录。",inputSchema:{type:"object",properties:{meal:{type:"string",enum:[...meals]}},required:["meal"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const v=input as {meal?:Meal};if(!v||Object.keys(v).length!==1||!meals.includes(v.meal as Meal))throw new Error("餐次无效");const s=stateRef.current;if(!s.ready)throw new Error("记录尚未准备好");s.startFood(v.meal as Meal);return {status:"form_opened",date:s.date,meal:v.meal}}}
 ]){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}return()=>lifecycle.abort()},[]);
 const displayed=(n:number,d=0)=>loading||loadError?"—":format(n,d);
 return <div className="app-shell"><Toaster position="top-center" richColors/><header className="topbar"><a className="brand" href="/" aria-label="Fuel Daily 首页"><span className="brand-icon"><PawPrint size={23}/></span>fuel<span className="brand-daily">daily</span></a><span className="nav-label">营养养成日记</span><span className="account"><span>今天也要认真吃饭</span><span className="avatar"><Leaf size={18}/></span></span></header>
 <main className="workspace"><div className="page-heading"><div><div className="eyebrow">FUEL DAILY · 养成日记</div><h1>今天，和{companion.name}一起<span className="title-dot">.</span></h1><p>记录每一餐，收获来自小伙伴的回应。</p></div><button className="button primary" disabled={!ready} onClick={()=>startFood(new Date().getHours()<11?"早餐":new Date().getHours()<16?"午餐":"晚餐")}><Plus size={18}/>记录饮食</button></div>
 <div className="date-bar"><div className="date-control"><button aria-label="前一天" disabled={!date||busy||date<="1900-01-01"} onClick={()=>setDate(shiftDate(date,-1))}><ChevronLeft size={18}/></button><label className="date-picker"><CalendarDays size={16}/><strong>{date===today?"今天":date.slice(5).replace("-","月")+"日"}</strong><input type="date" aria-label="选择记录日期" value={date} min="1900-01-01" max={today} disabled={busy} onChange={e=>{if(e.target.value&&e.target.validity.valid)setDate(e.target.value)}}/></label><button aria-label="后一天" disabled={!date||date>=today||busy} onClick={()=>setDate(shiftDate(date,1))}><ChevronRight size={18}/></button></div><span className="quiet date-readable">{readable}</span>{date!==today&&<button className="today-button" disabled={busy} onClick={()=>setDate(today)}>回到今天</button>}<button className="text-button" disabled={!ready} onClick={startGoals}><SlidersHorizontal size={16}/>调整目标</button></div>
 {loadError&&<div className="error-banner" role="alert"><span>{loadError}</span>{needsLogin?<a className="button primary" href="/signin-with-chatgpt?return_to=/" target="_top">登录并继续</a>:<button className="button" onClick={()=>refresh(date)}>重新加载</button>}</div>}
 <NutritionPet key={date} species={species} onSpeciesChange={switchPet} pet={data.pet??initialPet} ready={ready} loading={loading} failed={!!loadError} reaction={petReaction} historical={date!==today} onFeed={()=>startFood(new Date().getHours()<11?"早餐":new Date().getHours()<16?"午餐":"晚餐")}/>
 <div className="dashboard" aria-busy={loading}><section className="main-column"><div className="overview card"><div className="section-line"><h2><Flame size={18}/>热量摄入</h2><span className="small-label">DAILY ENERGY</span></div><div className="energy-content"><div><div className="energy-value">{displayed(totals.calories)}<span>kcal</span></div><p className="quiet">每日目标 {format(g.calories)} kcal</p><div className={"remaining "+(totals.calories>g.calories?"over":"")}><ArrowUpRight size={18}/>{totals.calories>g.calories?"超出目标":"还可摄入"} <b>{displayed(Math.abs(g.calories-totals.calories))}</b> kcal</div></div><div className="energy-ring" role="img" aria-label={"热量目标完成度 "+(loading?"加载中":progress+"%")}><svg viewBox="0 0 160 160"><circle cx="80" cy="80" r="68"/><circle className="energy-ring-fill" cx="80" cy="80" r="68" strokeDasharray="427.26" strokeDashoffset={427.26*(1-Math.min(progress,100)/100)} style={{opacity:progress&&!loading&&!loadError?1:0}}/></svg><div><strong>{loading||loadError?"—":progress}<span>%</span></strong><span>目标完成度</span></div></div></div><div className="macros">{([["protein","蛋白质","PROTEIN"],["carbs","碳水化合物","CARBS"],["fat","脂肪","FAT"]] as const).map(([key,name,en])=><div className={"macro "+key} key={key}><div className="macro-label"><span>{name}</span><span>{en}</span></div><div className="macro-number">{displayed(totals[key],1)} <small>/ {format(g[key],1)} g</small></div><Progress aria-label={name+"目标完成度"} value={loading||loadError?0:Math.min(100,totals[key]/g[key]*100)}/><p>{totals[key]>g[key]?"超出":"还差"} {displayed(Math.abs(g[key]-totals[key]),1)} g</p></div>)}</div></div>
 <div className="section-heading"><h2>饮食日志</h2><span className="quiet">{loading?<><LoaderCircle size={14} className="spin"/> 正在读取</>:loadError?"尚未加载":data.entries.length+" 条记录"}</span></div>
 <div className="meal-list card">{meals.map((m,i)=>{const entries=data.entries.filter(e=>e.meal===m);const Icon=icons[i];return <div className="meal-section" key={m}><div className="meal"><span className={"meal-icon meal-"+i}><Icon size={21}/></span><div><h3>{m}</h3><p>{loading?"正在读取…":loadError?"等待加载":entries.length?entries.length+" 项食物":"还没有记录"}</p></div>{entries.length>0&&!loading&&!loadError&&<span className="meal-total">{format(totalEntries(entries).calories)} <small>kcal</small></span>}<button aria-label={"添加"+m} className="add-meal" disabled={!ready} onClick={()=>startFood(m)}><Plus size={19}/></button></div>{!loading&&!loadError&&entries.map(e=><div className="food-row" key={e.id}><div className="food-info"><strong>{e.name}</strong><span className={"food-kind-tag kind-"+(e.foodKind??"regular")}>{foodKindInfo[e.foodKind??"regular"].short}</span><p>{format(e.grams,1)} g <span>· 蛋白质 {format(e.protein,1)} g · 碳水 {format(e.carbs,1)} g · 脂肪 {format(e.fat,1)} g</span></p></div><span className="food-energy">{format(e.calories)} <small>kcal</small></span><div className="food-actions"><button aria-label={"编辑"+e.name} disabled={!ready} onClick={()=>startEdit(e)}><Pencil size={14}/></button><button aria-label={"删除"+e.name} disabled={!ready} onClick={()=>deleteEntry(e)}><Trash2 size={14}/></button></div></div>)}</div>})}</div>
 {!loading&&!loadError&&data.entries.length===0&&<Empty className="journal-empty"><EmptyDescription>{companion.name}的小碗还空着，从第一餐开始吧。</EmptyDescription></Empty>}
 <div className="save-status">{loading?<LoaderCircle className="spin" size={14}/>:<CloudCheck size={14}/>}<span>{loading?"正在同步记录":loadError?"连接后即可保存":data.entries.length||water?"记录已保存到你的账户":"每次记录后自动保存"}</span></div></section>
 <aside className="side-column"><div className="target-card"><span className="small-label">ONE DAY AT A TIME</span>{data.goalsSet?<><span className="goal-badge"><Target size={13}/>{g.mode}</span><h2>按自己的节奏<br/>靠近目标</h2><p>每日 {format(g.calories)} kcal<br/>蛋白质目标 {format(g.protein)} g</p></>:<><h2>你的目标<br/>从今天开始</h2><p>先设置每日摄入目标，<br/>再用每一餐积累你的进度。</p></>}<button className="button dark" disabled={!ready} onClick={startGoals}>{data.goalsSet?"管理我的目标":"设置我的目标"} <ArrowUpRight size={18}/></button><div className="target-footer">{data.goalsSet?"记录 · 了解 · 调整":"当前为示例目标，可自行调整"}</div></div>
 <div className="water card"><div className="section-line"><h2><Droplets size={18}/>饮水记录</h2><span className="water-unit">ml</span></div><div className="water-value">{displayed(water)} <small>/ {format(g.water)}</small></div><Progress aria-label="饮水目标完成度" value={loading||loadError?0:Math.min(100,water/g.water*100)}/><div className="water-glasses" aria-hidden="true">{Array.from({length:8},(_,i)=><Droplets key={i} size={23} className={!loading&&!loadError&&water/g.water>i/8?"full":""}/>)}</div><button className="button water-button" disabled={!ready} onClick={drink}><Plus size={17}/>喝了一杯 <span>250 ml</span></button>{water>0&&!loading&&!loadError&&<button className="undo-water text-button" disabled={!ready} onClick={undoWater}><RotateCcw size={12}/>撤销上一杯</button>}</div><div className="note"><span className="note-marker"/><p>记录真实的每一天。<br/><span>不必完美，持续就很棒。</span></p></div></aside></div><footer>FUEL DAILY <span>一人一宠，一起把日子吃得有滋有味。</span></footer></main>
 <Dialog open={foodOpen} onOpenChange={v=>{if(!busy)setFoodOpen(v)}}><DialogContent className="nutrition-dialog" showCloseButton={false}><DialogHeader><DialogTitle>{editing?"编辑饮食记录":"记录一餐"}</DialogTitle><DialogDescription>{readable} · 按实际吃下的份量记录</DialogDescription></DialogHeader><DialogClose className="dialog-close" aria-label="关闭" disabled={busy}><X size={19}/></DialogClose><form onSubmit={saveFood}><div className="field"><label>记录到</label><Select value={meal} onValueChange={v=>setMeal(v as Meal)} disabled={busy}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{meals.map(m=><SelectItem key={m} value={m}>{m}</SelectItem>)}</SelectContent></Select></div>
 <Tabs value={tab} onValueChange={v=>{setTab(v);setFoodKind(v==="common"&&selected?"nourishing":"regular");setFormError("")}}><TabsList className="food-tabs"><TabsTrigger value="common">常用食物</TabsTrigger><TabsTrigger value="custom">手动填写</TabsTrigger></TabsList>
 <TabsContent value="common"><div className="field"><label htmlFor="food-search">选择食物</label><Combobox items={foods.map(f=>f.name)} value={selected} onValueChange={v=>{setSelected(v);const f=foods.find(f=>f.name===v);if(f){setGrams(String(f.portion));setFoodKind("nourishing")}}}><ComboboxInput id="food-search" placeholder="搜索米饭、鸡蛋、鸡胸肉、燕麦…" disabled={busy}/><ComboboxContent><ComboboxEmpty>没有匹配食物，可切换「手动填写」。</ComboboxEmpty><ComboboxList>{(name:string)=><ComboboxItem key={name} value={name}>{name}</ComboboxItem>}</ComboboxList></ComboboxContent></Combobox></div>
 <div className="quick-foods">{foods.map(f=><button type="button" key={f.name} disabled={busy} className={selected===f.name?"active":""} onClick={()=>{setSelected(f.name);setGrams(String(f.portion));setFoodKind("nourishing")}}>{f.name.split(" · ")[0]}</button>)}</div>
 {selectedFood?<><div className="field"><label htmlFor="food-grams">食用重量 <span>g</span></label><input id="food-grams" type="number" inputMode="decimal" required min="0.1" max="10000" step="0.1" value={grams} onChange={e=>setGrams(e.target.value)} disabled={busy}/><p className="field-help">{selectedFood.hint}</p></div><div className="nutrition-preview">{nutrients.map(([key,label,unit])=><div key={key}><span>{label}</span><strong>{format(scale(selectedFood[key],Number(grams)||0),key==="calories"?0:1)}<small>{unit}</small></strong></div>)}</div><p className="food-source">参考数据用于估算，烹饪方式与品牌会影响数值。<a href={selectedFood.source} target="_blank" rel="noreferrer">查看数据来源 ↗</a></p></>:<Empty className="food-empty"><EmptyDescription>选择常用食物，自动按重量换算营养。</EmptyDescription></Empty>}</TabsContent>
 <TabsContent value="custom"><div className="field"><label htmlFor="custom-name">食物名称</label><input id="custom-name" required maxLength={80} placeholder="例如：全麦三明治" value={custom.name} onChange={e=>setCustom({...custom,name:e.target.value})} disabled={busy}/></div><div className="field"><label htmlFor="custom-grams">食用重量 <span>g</span></label><input id="custom-grams" type="number" inputMode="decimal" required min="0.1" max="10000" step="0.1" value={custom.grams} onChange={e=>setCustom({...custom,grams:e.target.value})} disabled={busy}/></div><p className="input-note">填写<strong>本次食用份量的总营养</strong>，不再按重量换算。</p><div className="nutrient-fields">{nutrients.map(([key,label,unit])=><div className="field" key={key}><label htmlFor={"custom-"+key}>{label} <span>{unit}</span></label><input id={"custom-"+key} type="number" inputMode="decimal" required min="0" max="100000" step="0.01" placeholder="0" value={custom[key]} onChange={e=>setCustom({...custom,[key]:e.target.value})} disabled={busy}/></div>)}</div></TabsContent></Tabs>
 <div className="pet-food-picker"><div className="pet-food-label"><PawPrint size={16}/><span>这餐，{companion.name}会怎么吃？</span></div><RadioGroup aria-label="宠物食物分类" value={foodKind} onValueChange={v=>setFoodKind(v as FoodKind)} className="pet-food-options" disabled={busy}>{foodKinds.map(k=><label key={k} className={"pet-food-option "+(foodKind===k?"chosen ":"")+"kind-"+k}><RadioGroupItem value={k} id={"kind-"+k}/>{k==="nourishing"?<Leaf size={18}/>:k==="regular"?<Sun size={18}/>:<Candy size={18}/>}<span>{foodKindInfo[k].label}</span></label>)}</RadioGroup><div className={"pet-food-reaction kind-"+foodKind}><Sparkles size={14}/><span>{foodKindInfo[foodKind].feedback}</span></div><p className="field-help">你可以按实际食物调整分类，仅影响宠物游戏。</p></div>
 {formError&&<p className="form-error" role="alert">{formError}</p>}<button className="button primary form-submit" type="submit" disabled={busy||(tab==="common"&&!selectedFood)}>{busy?<LoaderCircle size={17} className="spin"/>:<Check size={17}/>} {busy?"正在保存…":editing?"保存修改":"加入"+meal}</button></form></DialogContent></Dialog>
 <Dialog open={goalOpen} onOpenChange={v=>{if(!busy)setGoalOpen(v)}}><DialogContent className="nutrition-dialog" showCloseButton={false}><DialogHeader><DialogTitle>我的每日目标</DialogTitle><DialogDescription>填写适合自己的目标，从 {date} 起生效。</DialogDescription></DialogHeader><DialogClose className="dialog-close" aria-label="关闭" disabled={busy}><X size={19}/></DialogClose><form onSubmit={saveGoals}><div className="field"><label>当前方向</label><Select value={goalDraft.mode} onValueChange={v=>setGoalDraft({...goalDraft,mode:v})} disabled={busy}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{["保持状态","增肌","减脂"].map(m=><SelectItem value={m} key={m}>{m}</SelectItem>)}</SelectContent></Select><p className="field-help">方向用于标记，不会自动更改摄入目标。</p></div><div className="nutrient-fields">{[...nutrients,["water","饮水","ml"] as const].map(([key,label,unit])=><div className="field" key={key}><label htmlFor={"goal-"+key}>{label} <span>{unit}</span></label><input id={"goal-"+key} type="number" inputMode="decimal" required min="1" max={key==="water"||key==="calories"?20000:2000} step={key==="water"?"1":"0.1"} value={Number.isNaN(goalDraft[key])?"":goalDraft[key]} onChange={e=>setGoalDraft({...goalDraft,[key]:e.target.value===""?NaN:Number(e.target.value)})} disabled={busy}/></div>)}</div><p className="input-note">初始值为示例。你可以按已有的训练或饮食计划填写；之前日期的目标不会被覆盖。</p>{formError&&<p className="form-error" role="alert">{formError}</p>}<button className="button primary form-submit" type="submit" disabled={busy}>{busy?<LoaderCircle size={17} className="spin"/>:<Check size={17}/>} {busy?"正在保存…":"保存目标"}</button></form></DialogContent></Dialog></div>
}
