"use client";
import {useState,useEffect} from "react";
import {Heart,Sparkles,Leaf,Plus,PawPrint,Info,Star,Utensils,Droplets,X,Zap,Dog,Cat} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogClose} from "@/components/ui/dialog";
import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
import {Progress} from "@/components/ui/progress";
import {foodKindInfo,initialPet,pets,petSpecies,type PetState,type PetReaction,type PetSpecies} from "@/lib/pet";

export function NutritionPet({pet=initialPet,ready,loading,failed,reaction,onFeed,historical,species="capybara",onSpeciesChange}:{pet?:PetState;ready:boolean;loading:boolean;failed:boolean;reaction:PetReaction|null;onFeed:()=>void;historical:boolean;species?:PetSpecies;onSpeciesChange:(species:PetSpecies)=>void}){
 const companion=pets[species];
 const [petted,setPetted]=useState(false);const [effect,setEffect]=useState<PetReaction|null>(null);const [rules,setRules]=useState(false);
 useEffect(()=>{setPetted(false);setEffect(null)},[species]);
 useEffect(()=>{if(!reaction){setEffect(null);return}setEffect(reaction);const t=setTimeout(()=>setEffect(null),6500);return()=>clearTimeout(t)},[reaction]);
 useEffect(()=>{if(!petted)return;const t=setTimeout(()=>setPetted(false),2500);return()=>clearTimeout(t)},[petted]);
 const excited=petted||effect?.kind==="nourishing"||effect?.kind==="water";
 const appearance=effect?.kind==="treat"?"round":excited?(pet.roundness>=24?"round":"happy"):pet.appearance;
 const phrase=petted?companion.pat:effect?effect.kind==="water"?"咕嘟咕嘟，陪你喝水！":foodKindInfo[effect.kind].feedback:failed?"我在这里等你，连接后就能一起吃饭啦。":pet.feedCount===0?companion.greeting:pet.mood==="happy"?"这餐我喜欢！一起元气满满吧。":pet.mood==="full"?"肚肚圆了一点，下一餐清爽些吧～":"和你一起好好吃饭，是我的小确幸。";
 const moodLabel=excited||pet.mood==="happy"?"超开心":appearance==="round"?"圆滚滚":"期待投喂";
 return <><section id="pet-home" className={"pet-home "+(appearance==="round"?"pet-home-round":"")} aria-label={"营养宠物"+companion.name}>
 <div className="pet-intro"><div className="pet-eyebrow"><span><PawPrint size={15}/>我的营养搭子</span><span className="pet-live-label">{historical?"成长回忆":"一起长大"}</span></div><RadioGroup aria-label="选择营养伙伴" value={species} onValueChange={v=>{if(ready)onSpeciesChange(v as PetSpecies)}} orientation="horizontal" className="pet-species-picker" aria-disabled={!ready}>{petSpecies.map(s=>{const friend=pets[s];const Icon=s==="puppy"?Dog:s==="kitten"?Cat:PawPrint;return <label key={s} className={"pet-species-option "+(species===s?"selected":"")}><RadioGroupItem value={s} aria-label={"选择"+friend.label+friend.name}/><Icon size={18}/><span>{friend.label}<small>{friend.name}</small></span></label>})}</RadioGroup><div className="pet-title"><h2>{companion.name}<span>陪你认真吃每一餐</span></h2><span className="pet-level"><Star size={13} fill="currentColor"/>Lv.{pet.level}</span></div><div className="pet-speech" aria-live="polite" aria-atomic="true"><span>{phrase}</span></div><div className="pet-actions"><button className="button pet-feed" disabled={!ready} onClick={onFeed}><Utensils size={17}/>记录一餐，喂喂{companion.name}<Plus size={17}/></button><button className="pet-rules-button" aria-label="查看宠物养成规则" onClick={()=>setRules(true)}><Info size={17}/></button></div><p className="pet-footnote"><Heart size={13}/>切换小伙伴，成长和饮食记录都会保留</p></div>
 <div className="pet-stage"><span className="pet-mood-pill"><span className={appearance==="round"?"mood-amber":"mood-green"}/>{moodLabel}</span><span className="stage-spark spark-one"><Sparkles/></span><span className="stage-spark spark-two"><Star/></span><div className="pet-stage-platform"/><button className={"pet-character "+(excited?"pet-bounce":"pet-breathe")+(effect?.kind==="treat"?" pet-wobble":"")} onClick={()=>setPetted(true)} aria-label={"摸摸"+companion.name} title="点我，摸摸头"><span role="img" aria-label={companion.label+companion.name+"："+(appearance==="round"?"圆滚滚":appearance==="happy"?"开心":"期待投喂")} className={"pet-sprite pet-sprite-"+species+" sprite-"+appearance} style={{backgroundImage:"url("+companion.image+")"}}/></button>{(effect||petted)&&<div className={"pet-particles effect-"+(effect?.kind??"pat")} key={effect?.id??"pat"} aria-hidden="true">{[0,1,2,3,4].map(n=><Heart key={n} className={"particle particle-"+n} fill="currentColor"/>)}</div>}{effect&&<div className="pet-reward" key={effect.id}><Sparkles size={15}/>{effect.kind==="water"?"一起补水":effect.kind==="treat"?"肚肚变圆了 · 成长 +10":effect.kind==="nourishing"?"元气补给 · 成长 +10":"成长 +10"}</div>}<span className="pet-touch-hint">点点{companion.name}，摸摸头</span></div>
 <div className="pet-stats"><div className="pet-stat-heading"><span>{companion.name}的成长手账</span><PawPrint size={16}/></div><div className="pet-stat"><div><span><Zap size={14}/>活力值</span><strong>{loading||failed?"—":pet.vitality}<small>/ 100</small></strong></div><Progress aria-label="宠物活力值" value={loading||failed?0:pet.vitality} className="vitality-progress"/></div><div className="pet-stat"><div><span><Heart size={14}/>圆润度</span><strong>{loading||failed?"—":pet.roundness}<small>/ 100</small></strong></div><Progress aria-label="宠物圆润度" value={loading||failed?0:pet.roundness} className="roundness-progress"/></div><div className="pet-xp"><div><span>距离 Lv.{pet.level+1}</span><strong>{pet.feedCount%5} / 5 次记录</strong></div><Progress aria-label="宠物成长进度" value={pet.levelProgress}/></div><span className="pet-stat-note">体型与活力根据近 7 天记录变化</span></div></section>
 <Dialog open={rules} onOpenChange={setRules}><DialogContent className="nutrition-dialog pet-rules-dialog" showCloseButton={false}><DialogHeader><DialogTitle>和{companion.name}一起长大</DialogTitle><DialogDescription>食物分类用于宠物游戏，不是个人健康评分。</DialogDescription></DialogHeader><DialogClose className="dialog-close" aria-label="关闭"><X size={19}/></DialogClose><div className="pet-rules-list"><div><Leaf/><p><strong>营养餐：{companion.name}会开心</strong><span>蔬菜、全谷物、优质蛋白等。活力 +8，圆润度减少 12，最低为 0。</span></p></div><div><Utensils/><p><strong>日常餐：一起好好吃饭</strong><span>普通餐或不确定的食物可选此项。圆润度减少 2，活力不变。</span></p></div><div><Sparkles/><p><strong>甜饮 / 油炸：肚肚会变圆</strong><span>每条记录圆润度 +24、活力 -12。圆润度达到 24 时，{companion.name}会变成圆滚滚的样子。</span></p></div><div><Star/><p><strong>认真记录，就能一起升级</strong><span>每条饮食记录增加 10 成长值，每 5 条升一级。所有类别都能积累成长。</span></p></div></div><p className="input-note">体型和活力按所选日期近 7 天的记录计算，活力初始为 70，上限 100、下限 20。修改、删除或撤销记录会同步重新计算，不会重复喂养。旧记录默认归为日常餐，可在编辑中调整。三位伙伴共享这些成长记录，切换伙伴不会重置进度。</p></DialogContent></Dialog></>;
}
