import {z} from "zod";
import {database} from "@/db/raw";
import {getChatGPTUser} from "@/app/chatgpt-auth";
import {defaultGoals,meals} from "@/lib/nutrition";
export const dynamic="force-dynamic";
const dateSchema=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v+"T12:00:00Z");return !isNaN(d.getTime())&&d.toISOString().slice(0,10)===v&&v>="1900-01-01"&&v<="9999-12-31"},"日期无效");
const quantity=z.number().finite().min(0).max(100000);
const entrySchema=z.object({kind:z.literal("entry"),id:z.string().uuid(),date:dateSchema,meal:z.enum(meals),name:z.string().trim().min(1).max(80),grams:z.number().finite().min(0.1).max(10000),calories:quantity,protein:quantity,carbs:quantity,fat:quantity,source:z.string().max(500).optional()}).strict();
const waterSchema=z.object({kind:z.literal("water"),id:z.string().uuid(),date:dateSchema,amount:z.number().int().min(1).max(10000)}).strict();
const goalSchema=z.object({kind:z.literal("goals"),date:dateSchema,calories:z.number().finite().min(1).max(20000),protein:z.number().finite().min(1).max(2000),carbs:z.number().finite().min(1).max(2000),fat:z.number().finite().min(1).max(2000),water:z.number().int().min(1).max(20000),mode:z.enum(["保持状态","增肌","减脂"])}).strict();
const deleteSchema=z.object({kind:z.enum(["entry","water"]),id:z.string().uuid()}).strict();
function json(data:unknown,status=200){return Response.json(data,{status,headers:{"Cache-Control":"no-store"}})}
function failure(e:unknown){if(e instanceof z.ZodError)return json({error:"请检查填写的日期和数值。"},400);if(e instanceof SyntaxError)return json({error:"提交内容无效。"},400);console.error("Journal request failed",e);return json({error:"暂时无法保存或读取记录，请稍后重试。"},503)}
function crossOrigin(req:Request){const origin=req.headers.get("origin");return origin!==null&&origin!==new URL(req.url).origin}
export async function GET(req:Request){try{const user=await getChatGPTUser();if(!user)return json({error:"登录后即可保存和查看你的记录。"},401);const date=dateSchema.parse(new URL(req.url).searchParams.get("date"));const db=database();const [entries,water,goal]=await db.batch([db.prepare("SELECT id,date,meal,name,grams,calories,protein,carbs,fat,source FROM nutrition_entries WHERE user_id=? AND date=? ORDER BY created_at,id").bind(user.userId,date),db.prepare("SELECT id,amount FROM water_entries WHERE user_id=? AND date=? ORDER BY created_at,id").bind(user.userId,date),db.prepare("SELECT calories,protein,carbs,fat,water,mode FROM nutrition_goals WHERE user_id=? AND date<=? ORDER BY date DESC LIMIT 1").bind(user.userId,date)]);return json({entries:entries.results,waterEntries:water.results,goals:goal.results[0]??defaultGoals,goalsSet:goal.results.length>0})}catch(e){return failure(e)}}
export async function POST(req:Request){try{if(crossOrigin(req))return json({error:"请从当前页面提交。"},403);const user=await getChatGPTUser();if(!user)return json({error:"请先登录。"},401);const b=z.discriminatedUnion("kind",[entrySchema,waterSchema]).parse(await req.json());const db=database();if(b.kind==="entry"){await db.prepare("INSERT INTO nutrition_entries (id,user_id,date,meal,name,grams,calories,protein,carbs,fat,source,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING").bind(b.id,user.userId,b.date,b.meal,b.name,b.grams,b.calories,b.protein,b.carbs,b.fat,b.source??"",Date.now()).run()}else{await db.prepare("INSERT INTO water_entries (id,user_id,date,amount,created_at) VALUES (?,?,?,?,?) ON CONFLICT(id) DO NOTHING").bind(b.id,user.userId,b.date,b.amount,Date.now()).run()}return json({ok:true,id:b.id})}catch(e){return failure(e)}}
export async function PUT(req:Request){try{if(crossOrigin(req))return json({error:"请从当前页面提交。"},403);const user=await getChatGPTUser();if(!user)return json({error:"请先登录。"},401);const b=z.discriminatedUnion("kind",[entrySchema,goalSchema]).parse(await req.json());const db=database();if(b.kind==="entry"){const r=await db.prepare("UPDATE nutrition_entries SET date=?,meal=?,name=?,grams=?,calories=?,protein=?,carbs=?,fat=?,source=? WHERE id=? AND user_id=?").bind(b.date,b.meal,b.name,b.grams,b.calories,b.protein,b.carbs,b.fat,b.source??"",b.id,user.userId).run();if(!r.meta.changes)return json({error:"这条记录已不存在，请刷新页面。"},404)}else{await db.prepare("INSERT INTO nutrition_goals(user_id,date,calories,protein,carbs,fat,water,mode) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(user_id,date) DO UPDATE SET calories=excluded.calories,protein=excluded.protein,carbs=excluded.carbs,fat=excluded.fat,water=excluded.water,mode=excluded.mode").bind(user.userId,b.date,b.calories,b.protein,b.carbs,b.fat,b.water,b.mode).run()}return json({ok:true})}catch(e){return failure(e)}}
export async function DELETE(req:Request){try{if(crossOrigin(req))return json({error:"请从当前页面提交。"},403);const user=await getChatGPTUser();if(!user)return json({error:"请先登录。"},401);const b=deleteSchema.parse(await req.json());const sql=b.kind==="entry"?"DELETE FROM nutrition_entries WHERE id=? AND user_id=?":"DELETE FROM water_entries WHERE id=? AND user_id=?";await database().prepare(sql).bind(b.id,user.userId).run();return json({ok:true})}catch(e){return failure(e)}}
